### ISSUE TITLE
Group collision text in diagram captions

### ISSUE THREAD

**Issue by dormerod** [Kashomon/gpub#12]
When there's a ko or some other 'collision' in a game, the convention seems to be to group all the moves together in the diagram caption.

Currently GPub automatically generates a caption that labels collisions with something like:
    W82 at 74, B85 at 9, W88 at 74, B91 at 9, W94 at 74, B97 at 9...

But it would look nicer and more compact (and more similar to other books) if the output for was grouped as something like:
   W82, W88, W94 ... at 74.
   B85, B91, B97 ... at 9.

In this scenario, where a stone number is being used instead of 'a' like we did previously, it would be ok to make the 'at' number (e.g. 74 above) a stone too. Note that sometimes a ko is filled so the stones in the list won't always all be all the same color like in the example above.

**Comment by Kashomon** [comment]
Would the black and white stones be on different lines? or would it be like:

W82, B85, W88 at 74?

**Comment by dormerod** [comment]
On the same line, as in your example, seems fine and is common in other go books.

I've attached some typical examples from a few different Asian go books. Example 1 seems to be the most diverse. Where they're using a marker (e.g. triangle, square) it's because those stones were already on the board from a previous diagram.

Examples:
![example-1](https://cloud.githubusercontent.com/assets/7741478/9157642/54531722-3f49-11e5-8d4e-b1e5fa1e67ca.jpg)
![example-2](https://cloud.githubusercontent.com/assets/7741478/9157643/54a1a7c0-3f49-11e5-9968-0d28c508df4e.jpg)
![example-3](https://cloud.githubusercontent.com/assets/7741478/9157644/54ede7b6-3f49-11e5-9cfd-4e13c435614b.jpg)
