### ISSUE TITLE
Use 'instead of' rather than 'from' for move number in variation captions

### ISSUE THREAD

**Issue by dormerod** [Kashomon/gpub#13]
GPub captions variations with things like "Variation 1 from B3" (Black 3 = B3), which is a helpful innovation in go books, especially when there are many variations.

However, when replaying games from a draft book for the purpose of proofreading, it seems like it might be clearer/more intuitive to print the caption as "Variation 1 instead of W4" instead. This is because the first move shown in the variation is W1 and not B1.

This is a trivial example from the beginning of a game. The need for clarity becomes more important when diagrams get busier and variations more numerous later in a game commentary. It might also be possible to use "for" rather than "instead of", for brevity at the expense of grammar :)

I'm not certain whether this convention would be objectively helpful for other readers too, or whether it's highly subjective either way. Still it might be worth discussing.

**Comment by dormerod** [comment]
A key point I forgot to add about this is that with the current 'from' notation, the from move can actually end up being the last move two diagrams back. This happens when the variation is an alternative for the first move of the most recent diagram. This is what makes it confusing and is what made me notice it in the first place.

**Comment by Kashomon** [comment]
Really, the issue around this is that we need to make the ordering of diagrams less confusing. Some of that might be wording. Some of it might be an ordering issue. High priority for me to clarify.

**Comment by Kashomon** [comment]
I ended up using 'for' rather than 'instead of'.  We can switch back to 'instead of' if it turns of to be more clear.

**Comment by dormerod** [comment]
Prima facie 'for' sounds better. It's more compact :)
