### ISSUE TITLE
Chapter headings run off the page for two digit chapter numbers

### ISSUE THREAD

**Issue by dormerod** [Kashomon/gpub#14]
The H3 chapter headings currently seem to run off the page of the generated PDF when the chapter number is greater than 9.

This could be an issue with the chapter style, though I don't recall ever seeing this particular problem before about commit debb7f6fb9

**Comment by Kashomon** [comment]
I was looking at the memoir style (memoir.dtx). Looks like I can probably override the style there.

http://ftp.math.purdue.edu/mirrors/ctan.org/macros/latex/contrib/memoir/memoir.dtx
