### ISSUE TITLE
SGF numbering is ignored/overwritten by GPub

### ISSUE THREAD

**Issue by dormerod** [Kashomon/gpub#15]
If the diagrams in an SGF are already numbered, GPub ignores these numbers and overwrites them with its own numbering.

I don't think this is really a bug (in my mind it's a feature which corrects for human error), but it could be unexpected for the user in some cases, so we should be explicit that this is the default behavior.

An option to disable auto-numbering and use the numbering from the SGF could be a 'nice to have' (low priority) feature for later.

(Note: the author of a book probably wants to number the moves in the SGF anyway when working on it, otherwise it's incredibly hard to write comments referring to specific move numbers.)

**Comment by dormerod** [comment]
One practical example of where this behavior can be slightly problematic is in commentary of the early opening. Sometimes you want to refer back to moves which were already played in the previous diagram, but you can't because they've already been 'spent' in the auto-numbering logic.

The workaround is to just number the moves as A, B, C... instead of 1, 2, 3... so it's really just that the behavior may be unexpected to the author and they'll have to change their book a little after running it through GPub for the first time and seeing what happens.

**Comment by Kashomon** [comment]
I don't think I'll ever fix this, sorry. I would call this a feature rather than a bug. I've added some notes to the README.
