### ISSUE TITLE
Support for dashes

### ISSUE THREAD

**Issue by dormerod** [Kashomon/gpub#16]
A lot of word processors and typesetting programs seem to automatically convert the easily typed - (minus sign) to &ndash; (en dash) when it's surrounded on both sides with a space. They also seem to maintain the character as it is when it's used as-a-hyphen.

I think it's highly desirable for GPub to behave in this way too because it would make books look much more professional. Some authors may also want to be able to type an &mdash; (em dash), which could perhaps be specified with a -- (double minus) wrapped in spaces?

(Aside: currently it doesn't seem to be possible to type an en dash or em dash in an SGF and have it output properly in GPub.)

**Comment by Kashomon** [comment]
A conversion method would work best, I think. Where - and -- are convert to en and em dashes respectively.

**Comment by dormerod** [comment]
This isn't a blocking issue, but dealing with this before publishing is highly desirable in terms of finishing the book nicely.

**Comment by Kashomon** [comment]
This is already supported, by the nature of how latex handles these things.
- => hypen
-- => en-dash
--- => em-dash
