### ISSUE TITLE
The last move in the final diagram of a commentary should be three digits

### ISSUE THREAD

**Issue by dormerod** [Kashomon/gpub#21]
GPub currently does a good job of using three digit labels in diagrams only when displaying moves that are modulo 100 and using one or two digits the rest of the time.

Another case where a three digit move could be preferable is when displaying the final move of a game. The three digit label should probably be shown for the last move in the last *diagram* for each SGF.

In some commentaries (where extra variations are necessary to explain something like a resignation) the main branch might continue past the last move, but it won't be marked with any further headings. Currently GPub interprets this last heading as the final diagram and the following moves/comments as variations. I think the way it handles things now is the ideal behavior and final move three digit detection would make it even better.

**Comment by Kashomon** [comment]
Interesting idea

**Comment by Kashomon** [comment]
I've been thinking about this -- it's not trivial to determine which diagram is the last diagram: The trickiness lies in the fact that you could have variations _after_ the last move of the game. I.e., "Why did black resign? Here's why black resigned".

**Comment by dormerod** [comment]
True. I imagined that you could work it out based on the last move of the last *diagram* of a chapter. However, that's only when someone is following the writing style that we've been using and it's probably not a good idea reduce flexibility with those sorts of assumptions.

Ultimately it's not really that important. Let's put it on the backburner or close?
