### ISSUE TITLE
Allow user to control heading suppression

### ISSUE THREAD

**Issue by dormerod** [Kashomon/gpub#22]
At some point in the future, it would be a useful feature for an author to be able to suppress heading x and below from numbering/table of contents. Perhaps as a command line option?

This is a very low priority issue because it's easy to suppress the headings manually in the TeX file (with the * prefix), so I'm just recording it here for later.

**Comment by Kashomon** [comment]
I might file this in the category of: User should create his own template.

Part of the problem is at some point I should clearly define what's expected of the template, and what's expected of GPub. That would allow users to better create custom templates.

**Comment by dormerod** [comment]
That sounds reasonable.

**Comment by dormerod** [comment]
I no longer think this is an issue worth addressing. Section numbering can be suppressed by using H5 instead of H4 anyway and I can't see a good use case for suppressing chapters.
