### ISSUE TITLE
Add cropping-on-variations support

### ISSUE THREAD

**Issue by Kashomon** [Kashomon/gpub#24]
We should add support for cropping-on-variations.  Currently this is performed via box-cropping. It should eventually support minimal cropping.

Things left to do: consider labels, fix some problematic edge cases.

**Comment by Kashomon** [comment]
Only thing left to do: Support using more than stones (+labels, +marks).

**Comment by dormerod** [comment]
Adding support for other labels and marks is becoming a high priority from my perspective. The cropping is currently a little too overzealous for complicated game commentaries.
