### ISSUE TITLE
Minor working directory quirks with --output_file_name and autocompile

### ISSUE THREAD

**Issue by dormerod** [Kashomon/gpub#25]
If the user wants to output their book to (for example) a subdirectory, it can produce some unexpected output.

For example:

    usr@machine:/path$ book_gen.js file.sgf --output_file_name=./subdir/filename

GPub will (correctly) create filename.tex in /path/subdir, but when the arguments are passed to pdflatex for autocompilation, it writes its files to the working directory (/path/ in this case).

This is a low priority issue because the following works to achieve the desired result:

    usr@machine:/path/subdir$ book_gen.js ../file.sgf --output_file_name=filename

**Comment by Kashomon** [comment]
Thanks for the bug. Should be fixed now.
