### ISSUE TITLE
Hidden and temporary files get picked up by GPub inadvertently (causing errors)

### ISSUE THREAD

**Issue by dormerod** [Kashomon/gpub#27]
If book_gen.js is run on multiple files and there happen to be temporary files like file.sgf.swp present, those files are picked up too and this causes errors which prevent GPub from creating the book.

Since these sorts of files are sometimes left behind by applications and are typically hidden from the user by default, some users may become confused and feel that a particular directory is cursed ;)

At first I thought that this was happening because of issue #26, but even after correcting for the duplicate GN properties that the swap file created, and testing again, there were still errors.

It might be a good idea for GPub to ignore hidden files and/or be stricter about matching only the '.sgf' file extension.

**Comment by Kashomon** [comment]
ah, should be easy fixed

**Comment by Kashomon** [comment]
Thanks for your debugging work.

Fixed with: https://github.com/Kashomon/gpub/commit/05905c2b82cde24ce6ed96d90fc56694ab175155
