### ISSUE TITLE
Stonify all numbers in collision list (and a, b labels)

### ISSUE THREAD

**Issue by dormerod** [Kashomon/gpub#33]
Right now the collision labels say things like "B195, B203 at 173," but it might be better if the said "B195, B203 at **B**173," (stonifying the last number as well).

This would use less space and would (I think) look better. As a bonus, it might help with issues like #6 sometime down the track because it makes the width more predictable as a proportion of the board (which uses the same Go font).

There's are also cases where the last stone is *a* instead of a number.

n.b. I'm using B1 as a shorthand for a black stone with the number 1 on it.

**Comment by Kashomon** [comment]
Sounds good. We should probably also replace Black/White <Letter> in body text as well. I think I only replace numbers (although I could be wrong).

**Comment by dormerod** [comment]
At the moment, Black [number] and Black [CapitalLetter] are replaced in the body text, but Black [lowercaseLetter] isn't.

Now that we have a bit more practical experience with the writing part, I think it would be useful to broaden the match to replace single lowercase letters too (for when we need to talk about the existing stone collision labels which are added in lowercase automatically).

I can't see yet how this could lead to problems, given the rules of English grammar. (In theory there could be problems with other languages later, but that's very much later and GPub wouldn't be matching the words 'Black' and 'White' in that case anyway.)
