### ISSUE TITLE
Collision labels should match board labels

### ISSUE THREAD

**Issue by dormerod** [Kashomon/gpub#34]
Any logic which is applied for formatting board labels should ideally be applied to the collision labels too.

This means that if move 197 is represented as B97 on the board (and not B197), the labels in the collision list should ideally be similarly truncated.

**Comment by Kashomon** [comment]
How is this different from https://github.com/Kashomon/gpub/issues/33?

**Comment by dormerod** [comment]
#33 says that numbers that aren't stonified should be.

This issue says that when stonifying numbers, make sure they're formatted to be the same as the stone labels on the board. In other words, if 197 is represented as 97 on the board, then it should be 97 in the collision list and not 197.

**Comment by Kashomon** [comment]
I see, no let's keep them separate.

**Comment by dormerod** [comment]
One possible exception to the 'same logic for all stone labels' rule (from outside the collision list) is the initial variation caption which says:

Variation x for y

It might be a good idea to never truncate *y* because duplicating, say, *Variation x for 29* for moves 29, 129 and 229 could be more confusing than perspicacious overall. For the collision labels though, I think matching them to the board makes everything clearer to the reader, because you tend to look for the exact label listed when replaying a game with a ko.
