### ISSUE TITLE
Should license text be stored separately from copyright.json?

### ISSUE THREAD

**Issue by dormerod** [Kashomon/gpub#35]
If your license text is just something like "All rights reserved" then putting it in copyright.json is fine, but I think in many cases publishers are going to need more flexibility than that.

It might be worth looking for an optional file like license.md to make things cleaner, even though it should probably still be displayed on the copyright page. (Note that currently a newline character in copyright.json causes an error, so that could be a new issue depending on how this issue is resolved).

It probably doesn't matter whether someone is using Creative Commons or a more traditional copyright notice, because both approaches often result in a lengthy block of text on the copyright page. I'll comment with some examples below.

**Comment by dormerod** [comment]
Copyright © 2015 by William Shakespeare

All rights reserved. No part of this publication may be reproduced, distributed, or transmitted in any form or by any means, including photocopying, recording, or other electronic or mechanical methods, without the prior written permission of the publisher, except in the case of brief quotations embodied in critical reviews and certain other noncommercial uses permitted by copyright law. For permission requests, write to the publisher, addressed “Attention: Permissions Coordinator,” at the address below.

**Comment by dormerod** [comment]
Copyright © 2015 by Charles Dickens

This book is distributed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International license. That means:

**You are free to:**
* Share -- copy and redistribute the material in any medium or format
* Adapt -- remix, transform, and build upon the material

**Under the following conditions:**
* Attribution -- You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
* NonCommercial -- You may not use the material for commercial purposes.
* ShareAlike -- If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.
* No additional restrictions -- You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.

This is a human-readable summary of (and not a substitute for) the license, which may be found at: https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode
When giving credit for this original work, please attribute it to Charles Dickens and link to: https://example.com/

**Comment by Kashomon** [comment]
sounds reasonable, although I think your 2nd example is a little excessive. It should be sufficient to reference the canonical text.

**Comment by dormerod** [comment]
This is fixed by the changes in pull request #49 and a separate file is not required.
