### ISSUE TITLE
Support for a dedication page?

### ISSUE THREAD

**Issue by dormerod** [Kashomon/gpub#37]
It might also be good to support a file like dedication.md for dedications.

I haven't done exhaustive research, but usually these appear after the copyright page and before the contents page. I've also seen some people put short dedications at the top of the copyright page, but I don't think that's necessarily a good idea.

What do you think about supporting dedications (as something distinct from acknowledgements) and does the CMoS say anything about them?

**Comment by Kashomon** [comment]
"Choice of dedication -- including whether to include one or now -- is up to the author.  It may be suggested, however, that the word dedicated is superfluous." 

If you want a dedication for the GGG books, sure, I'll add support. Otherwise, I'll probably ignore this feature request for now.

**Comment by dormerod** [comment]
Thanks for the CMoS advice.

I don't have strong feelings about a dedication page, but it's also a choice for you and Younggil to make. Family members do put up with a lot.

I think dedications (more than the core contributor list in #36) is something that could be done under acknowledgements, so there's no urgent need for a separate section.

**Comment by Kashomon** [comment]
SGTM, since we already have an acknowledgements, probably sufficient for now.
