### ISSUE TITLE
Cropping sometimes ignores moves in a variation

### ISSUE THREAD

**Issue by dormerod** [Kashomon/gpub#38]
This seems to be an edge case and has proven very difficult to deliberately reproduce so far.

You can see the bug for yourself by processing [this SGF](https://github.com/gogameguru/ggg-projects/blob/f83914b1d063a68d56682e9d5d4f4ddaf2f480c2/relentless/02-february.sgf) with the following arguments:

    --auto_box_crop_on_variation=true --region_restrictions=TOP,BOTTOM

The variation at the bottom of page 58 is missing Black 3.

**Comment by Kashomon** [comment]
oh, ha. I think I know what the problem is.

**Comment by Kashomon** [comment]
Totally rewrote the cropping logic. Let me know if you still see problems.
