### ISSUE TITLE
Lists cause a markdown error

### ISSUE THREAD

**Issue by dormerod** [Kashomon/gpub#47]
Ordered and unordered lists that look like:

    1. foo
    2. bar
    3. blah

and

    - foo
    - bar

or

    * foo
    * bar

Cause a marked error in GPub:

    ¡p¿An error occured:¡/p¿¡pre¿ordererd is not defined Please report this to https://github.com/chjj/marked.¡/pre¿

This isn't a blocking issue because it can be avoided by using an a. b. c. list and lists are relatively rare in Go books (so far there is only one in Relentless).

If it's an easy fix, it might make the formatting look a bit nicer on one page, but we can live without it.

**Comment by Kashomon** [comment]
Huh. I'll take a look
