### ISSUE TITLE
Support for Glossary

### ISSUE THREAD

**Issue by dormerod** [Kashomon/gpub#50]
Support for a glossary is a blocking issue. 

I had a go at fixing this and it seems like the simplest way to make this work without major changes is to define 'glossary' as an element of frontmatter for now. I think this saves adding redundant code to the LaTeX generator.

I'll send you a pull request for some code that works and if you're happy with it, it will be good enough for now.

**Comment by Kashomon** [comment]
Basic support added in: https://github.com/Kashomon/gpub/commit/89e7392037662952b31413b7ed4474f70ae50f62
