### ISSUE TITLE
GPub should be able to create tex fragments

### ISSUE THREAD

**Issue by amj** [Kashomon/gpub#55]
It'd be nice to not make a whole book out of a SGF, maybe just a few diagrams that could be \input into an existing tex shibboleth.  Thanks!

**Comment by Kashomon** [comment]
This is now done via renderDiagramsStream(fn) or renderDiagramsStream(fn, opt)

A worked example: https://github.com/Kashomon/gpub-examples/blob/master/streamed-example/index.js
