### ISSUE TITLE
Whitespace at the start of markdown causes an error

### ISSUE THREAD

**Issue by dormerod** [Kashomon/gpub#9]
If (for some reason) you put a space or other form of whitespace at the beginning of some text wrapped in markdown tags, it produces an error which appears in the output to the book.

Example:

    * hello*

The above text will cause an error.

This is perhaps not a GPub issue and could be reported to @chjj https://github.com/chjj/marked instead?

**Comment by Kashomon** [comment]
It's unfortunate, but not an issue with GPub, as you've mentioned.
